config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  resources :posts, only: [:create, :new, :show, :index, :edit, :destroy]

  resources :testimonials, only: [:create, :index, :new, :index, :edit, :destroy]



  patch '/posts/:id', to: 'posts#update'
  patch '/testimonials/:id', to: 'testimonials#update'


  devise_scope :user do
    get "/admin", to: "devise/sessions#new"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
  has_one_attached :image
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  has_rich_text :message
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @testimonials = Testimonial.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    # The @post variable is already set in the before_action callback
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # The @post variable is already set in the before_action callback
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :image)

  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if User.count == 1
      if user_signed_in?
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end
  end

end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:update, :edit, :destroy]

  def index
    @testimonials = Testimonial.all
  end

  def new
    @testimonial = Testimonial.new
  end


  def create
    @testimonial = Testimonial.create(testimonial_params)
    if @testimonial.save
      redirect_to testimonials_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    # The @testimonial variable is already set in the before_action callback
  end


  def update
    if @testimonial.update(testimonial_params)
      redirect_to root_path(anchor: 'testimonials')
    else
      render :edit
    end
  end


  def destroy
    @testimonial.destroy
    redirect_to posts_path
  end



  private


  def set_testimonial
    @testimonial = Testimonial.find(params[:id])
  end


  def testimonial_params
    params.require(:testimonial).permit(:message, :name, :photo, :company)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminVirtuosaWebSite</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= tinymce_assets %>
    <script type="text/javascript" src="/assets/tinymce.js"></script>

  </head>

  <body>
  <%= render  "shared/navbar" %>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


  </body>
</html>

app/views/pages/home.html.erb
<%# _____________ Banner ______________ %>

<div class="banner">
  <%= image_tag "logo.webp", class: "logo" %>
  <div class="container text-center">
    <h1 class="mb-4">WHAT WOULD IT BE LIKE TO HAVE YOUR BUSINESS RUNNING SMOOTHLY WITHOUT COMPROMISING YOUR MENTAL HEALTH?</h1>
    <a  class="btn btn-outline-dark btn-lg" href="#"> Let's chat!</a>
  </div>
</div>


<%# ABOUT SESSION %>
<div class="d-flex justify-content-around" id="about">
  <div class="left-pannel">
    <%= image_tag "l.jpg", class: "aboutImage"  %>
  </div>
  <div class="d-flex flex-column justify-content-center ms-5">
    <h1>About Us</h1>
    <p class="mt-4">Hi, I’m Louisa - an admin guru, owner, and founder of Admin Virtuosa. I’m a wife and mom to 2 children and I’m a natural helper and get-it-done kind of girl. Through a degree in Business Administration and over 15 years of experience in the field, I have learned how to efficiently handle business operations. This assures everything runs smoothly on your end, freeing you to conquer your goals and focus on the core aspects of your business. My passion for joining forces with business owners, as well as my understanding of how to work in a team environment, will help your employees grow and succeed, ensuring tasks are executed efficiently in all areas of your business. Admin Virtuosa is a result of my personal burnout, and our core value is “doing business the healthy way!”. Mental health is important, and I believe no one is meant to run a business on their own. Through the power of partnership, your business can flourish without the long-lasting effects of burnout.</p>
  </div>
</div>




<%# FACTS SESSION %>
<div class="colorSection">
  <div class="d-flex justify-content-around" id="facts">
    <div class="facts d-flex flex-column justify-content-center">
      <h1 class="d-flex justify-content-end">Facts About Us</h1>
      <p class="mt-4 d-flex justify-content-end">I was born and raised in Brooklyn, NYC but currently reside in British Columbia, Canada.</p>
      <p class="d-flex justify-content-end">I am fluent in both English and Spanish – I’m a Latina. A LATINA FROM BROOKLYN... YES I'M SASSY!</p>
      <p class="d-flex justify-content-end">I’m a HUGE mental health advocate – I’ve had my struggles.</p>
      <p class="d-flex justify-content-end">I absolutely hate the spotlight – You can usually find me behind the scenes.</p>
      <p class="d-flex justify-content-end">I LOVE COFFEE! Lattes and Macchiatos keep me going.</p>
    </div>
    <div class="factsImage d-flex flex-column justify-content-center">
      <%= image_tag "facts.jpg", class: "ms-5 factsPhoto"  %>
    </div>
  </div>
</div>

<%# SERVICES SESSION %>

<div id="services">


  <div class="servicesBody d-flex justify-content-center">
    <h1>Services</h1>
  </div>


  <div class="d-flex flex-column align-items-center">
    <h2>Business Management</h2>
    <p>Are you overwhelmed with all of the behind-the-scenes operations of your business? Tired of having crucial details getting missed amid all your busyness? This service is the perfect opportunity for you! We will free you up to be the face of the business without having to worry about day-to-day operations. Business Management packages include:</p>
  </div>

    <div class="d-flex justify-content-around">
      <%# OBM - FIRST SERVICE CARD %>
      <div class="card" style="width: 18rem;">
        <%= image_tag "peopleManagement.jpeg", class:"serviceCardsImage" %>
        <div class="card-body">
          <h2>People Management</h2>
          <p class="card-text">Is keeping track of daily duties, outsourcing, and hiring team members taking too much of your time? With this service we will take care of all these details, making sure your team is happy and motivated.</p>
        </div>
      </div>


    <%# OBM - SECOND SERVICE CARD %>

    <div class="card" style="width: 18rem;">
      <%= image_tag "projectManagement.jpeg", class:"serviceCardsImage" %>
      <div class="card-body">
        <h2>Project Management</h2>
        <p class="card-text">Feeling unable to accomplish everything in your vision for your company? We will stay on top of your projects or assist you in launching a business or program, from start to finish.</p>
      </div>
    </div>

    <%# OBM - THIRD SERVICE CARD %>



    <div class="card" style="width: 18rem;">
      <%= image_tag "sop.webp", class:"serviceCardsImage" %>
      <div class="card-body">
        <h2>Operations Management</h2>
        <p class="card-text">Looking to eliminate uncertainty and improve quality control? We can help you with that! We will ensure all your systems - for billing, client relationships, communications, and workflow are in place. This also includes Standard Operating Procedure implementation.</p>
      </div>
    </div>














</div>




























<%# Team Session %>
<div class="colorTeam" id="team">
  <div class="d-flex flex-column align-items-center justify-content-around">
    <h1 class="fw-bold py-5">MEET THE TEAM</h1>
  </div>
  <div class="row d-flex justify-content-around">
    <div class="col d-flex flex-column align-items-center p-5">
      <%= image_tag"huby.webp", class: "teamPictures" %>
      <h5>Scott Thiessen</h5>
      <p>Financial Manager, Sanity officer</p>
      <p><em>“Behind every successful woman, there’s a cheerleader”</em></p>
      <p class="teamParagraph">Scott is a vital part of Admin Virtuosa. He makes sure the business is running smoothly by being the right hand of our owner Louisa. As Louisa’s husband, Scott helps keep her sane by making sure she honors her boundaries and giving her pep talks when things get hard, which makes him the perfect sanity officer (yes we made up that position). Scott has a great eye for details and is great with numbers making him the perfect financial manager. He loves all things sports and is a huge football fan… GO GIANTS!!!</p>

    </div>

    <div class="col d-flex flex-column align-items-center p-5">
      <%= image_tag"filipa.webp", class: "teamPictures" %>
      <h5>Filipa Merino</h5>
      <p>Social Media Manager</p>
      <p> <em>"Successful Social Media marketing is built on relationships"</em></p>
      <p class="teamParagraph" class="teamParagraph">Filipa handles all social media things. She currently manages the Admin Virtuosa Instagram page, and she is also the brains behind our website as well – SHE DID THAT! She is a go-getter who loves to learn and help. She is also a huge mental health advocate, making her the team's perfect addition.

    </div>
  </div>
</div>

<%# TESTIMONIALS %>
<%= render  "testimonials/testimonials"%>
<%# CONTACTS %>

<section class="container-fluid row d-flex flex-row py-5" id="contacts">

  <div class="col-lg-12 col-sm-12">
    <h1 id="contact-title" class="d-flex flex-row align-items-center justify-content-center display-5 fw-bold lh-1 mt-3 mb-3">Contact Us</h1>
  </div>


  <div class="d-flex align-items-center justify-content-center py-3">

    <%= link_to "mailto:louisa@adminvirtuosa.com", class:"contactItem me-2" do %>
      <i class="fa-solid fa-envelope"></i>
    <% end %>
    <%= link_to "https://www.instagram.com/adminvirtuosa/", class:"contactItem me-2" do %>
      <i class="fa-brands fa-instagram"></i>
    <% end %>
    <%= link_to "https://www.facebook.com/adminvirtuosa", class:"contactItem" do %>
      <i class="fa-brands fa-facebook"></i>
    <% end %>

  </div>


  <div class="d-flex justify-content-center">
    <p>Langley, British Columbia | Available worldwide | (604)-908-4805</p>
  </div>

  <div class="d-flex justify-content-center">


  <%= link_to "https://www.honeybook.com/widget/lava_virtual_assistance_183635/cf_id/628d3ba43cabd50ba12cb036", class: "chatButton" do %>
    <button class="btn btn-outline-dark btn-lg mt-1 d-flex justify-content-center">Let's chat!</button>
  <% end %>
  </div>



</section>

app/views/posts/_form.html.erb
<div>
  <%= simple_form_for post do |f| %>
    <div class="addInputs">
        <%= f.input :title,
                    class:"input-text js-input",
                    id:"title",
                    label: "Title",
                    input_html: { class: "form-control" } %>
        <%= f.rich_text_area :content,
                             input_html: { class: "trix-content form-control" }%>

        <%= f.input :image,
                    class:"input-text js-input",
                    label: "Image",
                    as: :file,
                    input_html: { class: "form-control" } %>

        <div class="d-flex justify-content-end">

          <%= f.submit class:"btn btn-primary mt-2" %>

        </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render "form", post:@post %>

app/views/posts/index.html.erb
<body class="postsIndexBody">

  <% if user_signed_in? %>
    <%= link_to new_post_path, class: "btn" do %>
      <i class="fa-solid fa-circle-plus ms-3"></i>
    <% end %>
  <% end %>

  <div class="postsBody">

  <% @posts.each do |post| %>
    <div class="d-flex justify-content-center mb-5">
      <div class="d-flex flex-column postContent">
        <h2 class="d-flex justify-content-center"><%= link_to post.title, post_path(post), class:"titlePosts mb-4" %></h2>

        <div class="position-relative">
          <% if user_signed_in? %>
            <div class="d-flex justify-content-end position-absolute ms-2 mt-2">
              <%= link_to edit_post_path(post) do %>
                <p class="indexPostsLinks"><i class="fa-solid fa-pen-to-square"></i></p>
              <% end %>
              <%= link_to post_path(post), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post?"} do %>
                <p class="indexPostsLinks ms-2"><i class="fa-solid fa-trash"></i></p>
              <% end %>
            </div>
          <% end %>
          <% if post.image.attached? %>
            <%= link_to post_path(post) do %>
              <%= cl_image_tag post.image.key, class: "indexPostImage d-flex justify-content-center mb-3" %>
            <% end %>
          <% end %>
        </div>

          <%# This line means that if the post has more than 230 characters, the post will be cut  %>
          <% if post.content.to_s.length > 230 %>
            <p class="d-flex justify-content-center">
              <%= link_to truncate(strip_tags(post.content.to_s), length: 230), post_path(post), class:"titlePosts mb-2" %></p>

                <div class="infoPostParagraph d-flex justify-content-between">
                  <%= link_to post_path(post), class:"readMoreLink" do %>
                    <p>Read More</p>
                  <% end %>
                  <%# <p class="dateParagraph"><%= post.date.strftime('%B %d, %Y')</p> %>
                </div>

          <% else %>
            <p class="d-flex justify-content-center">
              <%= link_to post.content, post_path(post), class:"titlePosts mb-2" %></p>
                <div class="infoPostParagraph d-flex justify-content-between">
                  <%= link_to post_path(post), class:"readMoreLink" do %>
                    <p>Read More</p>
                  <% end %>
                  <%# <p class="dateParagraph"><%= post.date.strftime('%B %d, %Y')</p> %>
                </div>
          <% end %>
          <hr>
        </div>
      </div>
    <% end %>
  </div>
</body>

app/views/posts/new.html.erb
<body class="addPosts">



  <div class="d-flex justify-content-center my-5 sessionLogin">
    <div class="col-6 newSessionLogin">
      <div class="d-flex flex-column my-5 mx-5 align-items-center">


        <h1>Add New Post</h1>

        <%= render "form", post: @post %>
      </div>
    </div>
  </div>



</body>

app/views/posts/show.html.erb
<body class="postsIndexBody">


  <div class="d-flex justify-content-start">
    <%= link_to posts_path do %>
      <p class="backLink"><i class="fa-solid fa-circle-arrow-left"></i></p>
    <% end %>
  </div>

  <div class="postShowBody">

    <div class="d-flex flex-column">
      <div class="d-flex flex-column align-items-center">
        <h2><%= @post.title %></h2>

        <div class="d-flex justify-content-center">
          <% if @post.image.attached? %>
            <%= cl_image_tag @post.image.key, class: "showImagePost my-4" %>
          <% end %>
        </div>

        <p class="postContentParagraph"><%= @post.content %></p>
        <%# <p class="dateParagraph d-flex justify-content-end"><%= @post.date.strftime('%B %d, %Y')</p> %>
      </div>
    </div>
  </div>


    <% if user_signed_in? %>

      <div class="d-flex justify-content-center">
        <%= link_to edit_post_path(@post) do %>
          <p class="linkParagraph"><i class="fa-solid fa-pen-to-square"></i></p>
        <% end %>
        <%= link_to post_path(@post), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post?"} do %>
          <p class="linkParagraph ms-1"><i class="fa-solid fa-trash"></i></p>
        <% end %>
      </div>
    <% end %>
</body>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
      <h1>ADMIN VIRTUOSA</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "About", "#about", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Services", "#services", class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Blog", posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", "#team", class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Contacts", "#contacts", class: "nav-link" %>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, class: "nav-link", data: {turbo_method: :delete} do %>
                <i class="fa-solid fa-right-from-bracket"></i>
              <% end %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#about", class: "dropdown-item" %>
              <%= link_to "Another action", "#services", class: "dropdown-item" %>
              <%= link_to "Another action", "#team", class: "dropdown-item" %>
              <%= link_to "Another action", "#contactss", class: "dropdown-item" %>


            </div>
          </li>




        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/testimonials/_form.html.erb
<div>
  <%= simple_form_for testimonial do |f| %>
    <div class="addInputs">

        <%= f.rich_text_area :message %>

        <%= f.input :photo, as: :file, input_html: { class: "form-control" } %>

        <%= f.input :name,
                    class:"input-text js-input",
                    id:"name",
                    label: "Name",
                    input_html: { class: "form-control" } %>

        <%= f.input :company,
                    class:"input-text js-input",
                    id:"company",
                    label: "company",
                    input_html: { class: "form-control" }  %>

        <div class="d-flex justify-content-end">

          <%= f.submit class:"btn btn-primary mt-2" %>

        </div>
    </div>
  <% end %>
</div>


<div>

app/views/testimonials/_testimonials.erb
<section id="testimonials">

  <div class="d-flex align-items-center justify-content-center">

    <h1 class="fw-bold d-flex justify-content-center py-4">TESTIMONIALS</h1>
  <%# If user is signed in, show add testimonial button %>
    <% if user_signed_in? %>
      <%= link_to new_testimonial_path, class: "btn" do %>
        <i class="fa-solid fa-circle-plus"></i>
      <% end %>
    <% end %>
</div>
<%# For each testimonial do a carousel item %>

  <div id="caroussel" class="carousel slide justify-content-center my-auto" data-bs-ride="false">
    <div class="carousel-inner">
      <% @testimonials.each_with_index do |testimonial, i| %>
        <div class="carousel-item <%= "active" if i==0 %> ">
          <div class="d-flex flex-column align-items-center">
            <p><%= testimonial.message %></p>
            <% if testimonial.photo.attached? %>
              <%= cl_image_tag testimonial.photo.key, class: "testimonialImage" %>
            <% end %>

            <h4><%= testimonial.name %></h4>
            <h6><%= testimonial.company %></h6>

<%# This line of code means that if the user is signed in, delete and edit buttons should be displayed  %>
            <% if user_signed_in? %>
              <div class="d-flex">
                <%= link_to testimonial_path(testimonial), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                  <i class="fa-solid fa-trash bin"></i>
                <% end %>
                <%= link_to edit_testimonial_path(testimonial) do %>
                  <i class="fa-solid fa-pen-to-square editPen"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>



    <button class="carousel-control-prev" type="button" data-bs-target="#caroussel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#caroussel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</section>

app/views/testimonials/index.html.erb
<section id="testimonials">

  <div class="d-flex align-items-center justify-content-center">

    <h1 class="fw-bold d-flex justify-content-center py-4">TESTIMONIALS</h1>
  <%# If user is signed in, show add testimonial button %>
    <% if user_signed_in? %>
      <%= link_to new_testimonial_path, class: "btn" do %>
        <i class="fa-solid fa-circle-plus"></i>
      <% end %>
    <% end %>
</div>
<%# For each testimonial do a carousel item %>

  <div id="caroussel" class="carousel slide justify-content-center my-auto" data-bs-ride="false">
    <div class="carousel-inner">
      <% @testimonials.each_with_index do |testimonial, i| %>
        <div class="carousel-item <%= "active" if i==0 %> ">
          <div class="d-flex flex-column align-items-center">
            <p><%= testimonial.message %></p>
            <% if testimonial.photo.attached? %>
              <%= cl_image_tag testimonial.photo.key, class: "testimonialImage" %>
            <% end %>

            <h4><%= testimonial.name %></h4>
            <h6><%= testimonial.company %></h6>

<%# This line of code means that if the user is signed in, delete and edit buttons should be displayed  %>
            <% if user_signed_in? %>
              <div class="d-flex">
                <%= link_to testimonial_path(testimonial), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                  <i class="fa-solid fa-trash bin"></i>
                <% end %>
                <%= link_to edit_testimonial_path(testimonial) do %>
                  <i class="fa-solid fa-pen-to-square editPen"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>



    <button class="carousel-control-prev" type="button" data-bs-target="#caroussel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#caroussel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</section>

app/views/testimonials/new.html.erb
<body class="addTestimonials">

  <div class="d-flex justify-content-center my-5 sessionLogin">
    <div class="col-6 newSessionLogin">
      <div class="d-flex flex-column my-5 mx-5 align-items-center">


        <h1 class="mb-5">Add New Testimonial</h1>

        <%= render "form", testimonial: @testimonial %>
      </div>
    </div>
  </div>



</body>